all:
  children:
    homelab:
      hosts:
        home-server:
          ansible_host: 192.168.1.112
          ansible_user: admin_dev
          ansible_connection: local
          ansible_become_password: "{{ home_sudo_password }}"
    vps:
      hosts:
        iceland-vps:
          ansible_host: "{{ iceland_vps_ip }}"
          ansible_user: root
          ansible_port: 2222
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          xray_sni: "www.microsoft.com"
        helsinki-vps:
          ansible_host: "{{ helsinki_vps_ip }}"
          ansible_user: root
          ansible_port: 2222
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          xray_sni: "www.vk.com"
        germany-vps:
          ansible_host: "{{ germany_vps_ip }}"
          ansible_user: root
          ansible_port: 2222
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          xray_sni: "www.vk.com"
